# GitHub dependabot 专用

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# dependabot.yml 文件的配置选项：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# 自定义依赖项更新：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates
# 管理依赖项更新的所有拉取请求：https://docs.github.com/zh/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "npm"
    directory: "/passport-ui"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "docker"
    directory: "/admin-server"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/gateway"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/passport"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/canal"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/file"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/master-data"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/user"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/webservice"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/websocket"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/wechat-miniprogram"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/wechat-offiaccount"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/xxl-job-admin"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "docker"
    directory: "/ui"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
